# Generated by Django 5.2.13 on 2026-05-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_contract_models", "0005_contractattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="auto_renew",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_type",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="contract",
            name="coverage_hours",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="contract",
            name="notice_period_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="response_time",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="contract",
            name="restoration_time",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="contract",
            name="term_months",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractassignment",
            name="coverage_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractassignment",
            name="coverage_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractassignment",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contractassignment",
            name="scope_notes",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
