# Generated by Django 5.2.13 on 2026-05-17 08:16

import django.db.models.deletion
import nautobot_contract_models.models.access_token
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0084_add_module_type_image_support"),
        ("nautobot_contract_models", "0009_alter_status_related_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ICalAccessToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=nautobot_contract_models.models.access_token._generate_token, max_length=64, unique=True
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_models_ical_token",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="CoverageSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("snapshot_date", models.DateField()),
                ("was_covered", models.BooleanField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_models_coverage_snapshots",
                        to="dcim.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date", "device"],
                "indexes": [
                    models.Index(fields=["-snapshot_date", "was_covered"], name="nautobot_co_snapsho_e56893_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot_date", "device"), name="nbcm_coveragesnapshot_unique_per_date_device"
                    )
                ],
            },
        ),
    ]
